# Site settings
title: "The Flucs Web Development"
description: "My resume for GitHub Pages site."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Web Developer"
resume_title:                   "Professional Frontend Developer"
resume_contact_email:           "sa.cux.dev@gmail.com.com"
resume_contact_telephone:       "+39 3922641302"
resume_contact_address:         "Cagliari, Sardinia"
resume_header_contact_info: "Cagliari, Sardinia | +39 3922641302 | sa.cux.dev@gmail.com.com"
resume_header_intro: "<p>Charting the knowledge of the Internet, just like Galileo charted the stars.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/theflucs"
  resume_twitter_url:           "http://twitter.com/the_flucs"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sabrinacuccureddu/"
  resume_instagram_url:         "https://www.instagram.com/saflucs/"
  # resume_website_url:           "insert your website URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
